# Generated by Django 4.0.2 on 2022-02-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plates', '0002_remove_plate_band_remove_plate_emulsion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Emulsion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emulsion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filt', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500, null=True)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('aperature', models.CharField(max_length=500, null=True)),
                ('scale', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('obs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plates.observatory')),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=3)),
                ('number', models.IntegerField()),
                ('ra', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('dec', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('jd', models.DecimalField(decimal_places=5, max_digits=13, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('exptime', models.IntegerField(null=True)),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plates.band')),
                ('emulsion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plates.emulsion')),
                ('filt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plates.filter')),
            ],
        ),
    ]
