# Generated by Django 4.0.2 on 2022-02-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0004_remove_plate_band_remove_plate_emulsion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Emulsion',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.DeleteModel(
            name='Observatory',
        ),
        migrations.DeleteModel(
            name='Plate',
        ),
        migrations.DeleteModel(
            name='Telescope',
        ),
    ]
