# Generated by Django 4.0.2 on 2022-02-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0005_repository_delete_band_delete_emulsion_delete_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
