# Generated by Django 4.0.2 on 2022-02-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0006_repository_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='desc',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
